server:
  port: 3001

spring:
  application:
    name: PRODUCT-SERVICE
  data:
    mongodb:
      host: localhost
      port: 27017
      database: productsDB

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service_url:
      default:zone: http://localhost:8761/eureka/
    instance:
      hostname: localhost
    server:
      wait-time-in-ms-when-sync-empty: 0



